# ---- Build stage ----
FROM node:20-alpine AS builder
WORKDIR /app

ENV = ""

# Copia sólo los archivos necesarios para instalar dependencias
COPY FrontEnd/package*.json ./FrontEnd/
RUN apk add --no-cache git

# Instala dependencias y construye
RUN npm ci --prefix ./FrontEnd
COPY FrontEnd ./FrontEnd
RUN npm run build --prefix ./FrontEnd

# ---- Runtime stage ----
FROM nginx:alpine AS runner

# Configuración de Nginx (SPA con fallback a index.html)
COPY FrontEnd/nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos el build generado
COPY --from=builder /app/FrontEnd/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]